version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7.25
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: morgana
      MYSQL_ROOT_PASSWORD: root
  app:
    image: app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db