version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7.25
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: morgana
      MYSQL_ROOT_PASSWORD: root
  app:
    image: app:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: morgana
    depends_on:
      - db

